### ISSUE TITLE
0.9 release checklist

### ISSUE THREAD

**Issue by littledivy** [denoland/deno_bindgen#138]
The latest rewrite brought a lot of breaking changes for users, for the better. It will be part of 0.9 stable.

- [ ] &str, String, Vec<T> and Box<T> support.

These types were removed in the new rewrite but for 0.9 stable I'd like to get them back so its less painful to migrate from 0.8.

**serde support has been removed**. This was a major cause of memory leaks and inefficient. It is recommended to use the new `impl` classes support instead.

- [ ] Explain publishing pipeline in docs / example.

**Automatic caching and fetching from GIthub releases has been removed**. This was awkward and offered very little flexibility. 

Instead, I've add support to lazy initialize the library; binary release, fetch and caching (if desired) is left to the user.

- [ ] Depreciate old CLI, print warning/error.

- [ ] Help other crates migrate to 0.9

Probably send a few PRs and open issues on active dependent crates. It will also help identify bugs.

**Comment by Sleepful** [comment]
oh yeah could not use `&str` as param, instead had to use `&String` (the compiler built it fine but IDK if it actually works)
